const fallbackQuotes = [
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Where there is a will, there is a way.", author: "Angela Merkel" },
    { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
    { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
    { text: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone" },
    { text: "We become what we think about.", author: "Earl Nightingale" },
    { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
    { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
    { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt" },
    { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "You take your life in your own hands, and what happens? A terrible thing, no one to blame.", author: "Erica Jong" },
    { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
    { text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
    { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
    { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
    { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
    { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", author: "Leonardo da Vinci" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "In order to write about life first you must live it.", author: "Ernest Hemingway" },
    { text: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra" },
    { text: "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.", author: "Unknown" },
    { text: "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", author: "Leo Burnett" },
    { text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { text: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton" },
    { text: "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", author: "Hillary Clinton" },
    { text: "Don't settle for what life gives you; make life better and build something.", author: "Ashton Kutcher" },
    { text: "Everything negative – pressure, challenges – is all an opportunity for me to rise.", author: "Kobe Bryant" },
    { text: "I like criticism. It makes you strong.", author: "LeBron James" },
    { text: "You never really learn much from hearing yourself speak.", author: "George Clooney" },
    { text: "Life imposes things on you that you can't control, but you still have the choice of how you're going to live through this.", author: "Celine Dion" },
    { text: "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.", author: "John F. Kennedy" },
    { text: "Live for each second without hesitation.", author: "Elton John" },
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "Life is a succession of lessons which must be lived to be understood.", author: "Helen Keller" },
    { text: "My mama always said, life is like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump" },
    { text: "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny.", author: "Lao-Tze" },
    { text: "When we do the best we can, we never know what miracle is wrought in our life or the life of another.", author: "Helen Keller" },
    { text: "The healthiest response to life is joy.", author: "Deepak Chopra" },
    { text: "Life is like a coin. You can spend it any way you wish, but you only spend it once.", author: "Lillian Dickson" },
    { text: "The best portion of a good man's life is his little nameless, unencumbered acts of kindness and of love.", author: "Wordsworth" },
    { text: "In three words I can sum up everything I've learned about life: It goes on.", author: "Robert Frost" },
    { text: "Life is ten percent what happens to you and ninety percent how you respond to it.", author: "Charles Swindoll" },
    { text: "Keep calm and carry on.", author: "Winston Churchill" },
    { text: "Maybe that's what life is… a wink of the eye and winking stars.", author: "Jack Kerouac" },
    { text: "Life is a flower of which love is the honey.", author: "Victor Hugo" },
    { text: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "Marilyn Monroe" },
    { text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha" },
    { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
    { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
    { text: "Life would be tragic if it weren't funny.", author: "Stephen Hawking" },
    { text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
    { text: "The greatest pleasure in life is doing what people say you cannot do.", author: "Walter Bagehot" },
    { text: "It is our choices that show what we truly are, far more than our abilities.", author: "J. K. Rowling" },
    { text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso" },
    { text: "If you want to be happy, be.", author: "Leo Tolstoy" },
    { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
    { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
    { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "Here's to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes.", author: "Rob Siltanen" },
    { text: "It is better to be hated for what you are than to be loved for what you are not.", author: "Andre Gide" },
    { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "H. Jackson Brown Jr." },
    { text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare" },
    { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
    { text: "The future belongs to those who learn more skills and combine them in creative ways.", author: "Robert Greene" },
    { text: "Life is what happens to us while we are making other plans.", author: "Allen Saunders" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
    { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
    { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison" },
    { text: "If Life Were Predictable It Would Cease To Be Life, And Be Without Flavor.", author: "Eleanor Roosevelt" },
    { text: "The happiness of your life depends upon the quality of your thoughts", author: "Marcus Aurelius" },
    { text: "You have power over your mind, not outside events. Realize this, and you will find strength", author: "Marcus Aurelius" },
    { text: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult", author: "Seneca" },
    { text: "We suffer more in imagination than in reality", author: "Seneca" },
    { text: "If you want to improve, be content to be thought foolish and stupid", author: "Epictetus" },
    { text: "First say to yourself what you would be; and then do what you have to do", author: "Epictetus" },
    { text: "Someone is sitting in the shade today because someone planted a tree a long time ago", author: "Warren Buffett" },
    { text: "The most important investment you can make is in yourself", author: "Warren Buffett" },
    { text: "Risk comes from not knowing what you're doing", author: "Warren Buffett" },
    { text: "Your time is limited, so don't waste it living someone else's life", author: "Steve Jobs" },
    { text: "Stay hungry, stay foolish", author: "Steve Jobs" },
    { text: "Deciding what not to do is as important as deciding what to do", author: "Steve Jobs" },
    { text: "If you are not embarrassed by the first version of your product, you've launched too late", author: "Reid Hoffman" },
    { text: "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down", author: "Reid Hoffman" },
    { text: "Do not compare yourself with anyone in this world; if you do so, you are insulting yourself", author: "Bill Gates" },
    { text: "Its fine to celebrate success, but it is more important to heed the lessons of failure", author: "Bill Gates" },
    { text: "Patience is a key element of success", author: "Bill Gates" },
    { text: "I never lose. I either win or learn", author: "Nelson Mandela" },
    { text: "It always seems impossible until it's done", author: "Nelson Mandela" },
    { text: "He who conquers himself is the mightiest warrior", author: "Confucius" },
    { text: "Our greatest glory is not in never falling, but in rising every time we fall", author: "Confucius" },
    { text: "Man is disturbed not by things, but by the views he takes of them", author: "Epictetus" },
    { text: "Luck is what happens when preparation meets opportunity", author: "Seneca" },
    { text: "Discipline is choosing between what you want now and what you want most", author: "Abraham Lincoln" },
    { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe", author: "Abraham Lincoln" },
    { text: "Knowing yourself is the beginning of all wisdom", author: "Aristotle" },
    { text: "Excellence is not an act, but a habit", author: "Aristotle" },
    { text: "Do what you can, with what you have, where you are", author: "Theodore Roosevelt" },
    { text: "Believe you can and youare halfway there", author: "Theodore Roosevelt" },
    { text: "Success is a lousy teacher. It seduces smart people into thinking they cant lose", author: "Bill Gates" },
    { text: "The best way to predict the future is to create it", author: "Peter Drucker" },
    { text: "Work like there is someone working 24 hours a day to take it all away from you", author: "Mark Cuban" },
    { text: "It doesnt matter how many times you fail, you only have to be right once", author: "Mark Cuban" },
    { text: "Be so good they cant ignore you", author: "Steve Martin" },
    { text: "The man who moves a mountain begins by carrying away small stones", author: "Confucius" },
    { text: "Do not pray for an easy life, pray for the strength to endure a difficult one", author: "Bruce Lee" },
    { text: "If you spend your life trying to be good at everything, you will never be great at anything", author: "Naval Ravikant" },
    { text: "Escape competition through authenticity", author: "Naval Ravikant" },
    { text: "Earn with your mind, not your time", author: "Naval Ravikant" },
    { text: "A calm mind brings inner strength and self-confidence", author: "Dalai Lama" },
    { text: "Happiness is not something ready-made. It comes from your own actions", author: "Dalai Lama" },
    { text: "What you do every day matters more than what you do once in a while", author: "James Clear" },
    { text: "Your habits shape your identity, and your identity shapes your habits", author: "James Clear" },
    { text: "Great things are not done by impulse, but by a series of small things brought together", author: "Vincent Van Gogh" },
    { text: "Judge a man by his questions rather than by his answers", author: "Voltaire" },
    { text: "The price of discipline is always less than the pain of regret", author: "Jim Rohn" },
    { text: "Formal education will make you a living; self-education will make you a fortune", author: "Jim Rohn" }
];
